### ISSUE TITLE
Add typeorm middleware for connecting to a database

### ISSUE THREAD

**Issue by dbartholomae** [dbartholomae/lambda-middleware#14]
**Is your feature request related to a problem? Please describe.**
Many of our lambdas need to connect to a relational database with help of [typeorm](https://typeorm.io/). This logic could be abstacted out similar to middy's [db-manager](https://github.com/middyjs/middy/tree/1.0.0-beta/packages/db-manager). This should also allow to wire the database into a [dependency injection framework](https://github.com/typestack/typedi).

**Describe the solution you'd like**
A minimal version should work like this, reading the setup needed from the [typeorm-typical env vars](https://typeorm.io/#/using-ormconfig/using-environment-variables).
```typescript
export const handler = connectDatabase({
  container: Container
})
( ..)
```
Potentially should allow to [get credentials via AWS](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDS/Signer.html).

**Describe alternatives you've considered**
Potentially this should be more abstract, allowing other kinds of ORMs like [knex](http://knexjs.org/). Currently I think a simple middleware focussing only on typeorm makes more sense, with individual middlewares for individual ORMs.

**Comment by dbartholomae** [comment]
Closing this as there currently is no interest. Feel free to comment here if you think this should be opened again.

**Comment by amouly** [comment]
@dbartholomae I'm interested on this, both for Dependency Injection and also for TypeORM.

Is something created for this already?

**Comment by dbartholomae** [comment]
No one worked on this yet as far as I know.
