### ISSUE TITLE
jsonSerializer does not pass through correct event type

### ISSUE THREAD

**Issue by parkan** [dbartholomae/lambda-middleware#45]
## Describe the bug
Hello it's me again 🙂 

jsonSerializer (and I think some of the other middlewares as well) don't respect the pattern of generically passing the event from the previous middleware [described in the README](https://github.com/dbartholomae/lambda-middleware#writing-your-own-middleware) so the type information about the modified event is lost, replaced with base `APIGatewayEvent`

## To Reproduce
```js
compose(
  errorHandler(),
  jwtAuth(...),
  jsonSerializer()
)(handler) // the handler gets APIGatewayEvent without AuthorizedEvent
```

## Expected behavior
Type information is preserved in the chain

## Additional context
This should be a simple fix, replace

```
export const jsonSerializer = () => (
  handler: PromiseHandler<APIGatewayEvent, JSONObject | undefined>
) => 
...
```

with

```
export const jsonSerializer = () => (
  <E extends APIGatewayProxyEvent>(handler: PromiseHandler<APIGatewayEvent, JSONObject | undefined>): PromiseHandler<E, APIGatewayProxyResult> =>
...
```

happy to PR this!

**Comment by parkan** [comment]
seems that this exact configuration is used in https://github.com/dbartholomae/lambda-middleware/blob/main/internal/e2e-tests/examples/helloWorld.ts#L52 but the handler doesn't actually use anything other than `body` on the event, I can add a test for .auth/explicit event type expectation

**Comment by dbartholomae** [comment]
Unfortunately there is a limit to how TypeScript is implemented that currently makes it impossible to have a full 100% passthrough of events. This was discussed in detail in #36. Please feel free to play around with it a bit, maybe there is a way to improve it I didn't find :)

**Comment by parkan** [comment]
gotcha, gonna close this for now and mess around with it a bit
