### ISSUE TITLE
Allowing PromiseHandler to have generic Context

### ISSUE THREAD

**Issue by nateiler** [dbartholomae/lambda-middleware#49]
I might be missing something here, but what do you think about adding Context as a generic to the ProxyHandler.  I seem to hit a wall when altering it and passing those alterations to the next middleware.  

I followed the [instructions to creating middleware](https://github.com/dbartholomae/lambda-middleware#writing-your-own-middleware), but didn't see any references on how to alter the context.  As a result, I explored with adding a context generic to the [PromiseHandler](https://github.com/dbartholomae/lambda-middleware/blob/e9aa6ba1b924a8de2b48df74b1cd6852f85e6fc7/packages/utils/src/PromiseHandler.ts#L3)

New PromiseHandler
```typescript
export type ContextPromiseHandler<
  TEvent = any,
  TResult = any,
  TContext = Context
> = (event: TEvent, context: TContext) => Promise<TResult>;
```

And an example of altering the context 
```typescript

// Add `foo` to context
const fooContextMiddleware = () => <
  E extends APIGatewayProxyEvent,
  C extends Context
>(
  handler: ContextPromiseHandler<E, APIGatewayProxyResult, C & { foo: string }>
): ContextPromiseHandler<E, APIGatewayProxyResult, C> => async (
  event: E,
  context: C
) => {
  return handler(event, { ...context, foo: "bar" });
};

// Add `bar` to context
const barContextMiddleware = () => <
  E extends APIGatewayProxyEvent,
  C extends Context
>(
  handler: ContextPromiseHandler<E, APIGatewayProxyResult, C & { bar: string }>
): ContextPromiseHandler<E, APIGatewayProxyResult, C> => async (
  event: E,
  context: C
) => {
  return handler(event, { ...context, bar: "foo" });
};

// Business
const helloWorldContext = async (
  event: APIGatewayProxyEvent,
  context: Context & { foo: string; bar: string }
) => {
  console.log("Foo", context.foo);
  console.log("Bar", context.bar);

  return {
    body: "Hello World",
    statusCode: 200,
  };
};

// In strict mode so using
export const handler = composeHandler(
  fooMiddleware(),
  barMiddleware(),
  helloWorldContext
);

```

**Comment by dbartholomae** [comment]
Unfortunately, this is a limitation of TypeScript related to generics and not solvable by this library. You can find the relevant links and discussions here:
https://github.com/dbartholomae/lambda-middleware/issues/36#issuecomment-720755530
