### ISSUE TITLE
Middleware ordering causes type conflicts on remaining middleware 

### ISSUE THREAD

**Issue by nateiler** [dbartholomae/lambda-middleware#51]
I tried to follow the [bodyParser example](https://github.com/dbartholomae/lambda-middleware#writing-your-own-middleware) and build my own middleware which alters the event.  I was also adding the first party [cors middleware](https://github.com/dbartholomae/lambda-middleware/tree/main/packages/cors) to the routine which produced some type errors I cannot figure out.

In the first scenario, the first middleware is adding 'foo' to the event -> cors -> business logic which doesn't hold the type reference:

```typescript
import {
  Context,
  APIGatewayProxyEvent,
  APIGatewayProxyResult,
} from "aws-lambda";
import { PromiseHandler } from "@lambda-middleware/utils";
import { composeHandler } from "@lambda-middleware/compose";
import { cors } from "@lambda-middleware/cors";

const fooMiddleware = () => <E extends APIGatewayProxyEvent>(
  handler: PromiseHandler<E & { foo: string }, APIGatewayProxyResult>
): PromiseHandler<E, APIGatewayProxyResult> => async (
  event: E,
  context: Context
) => {
  return handler({ ...event, foo: "bar" }, context);
};

const helloWorldEvent = async (
  event: APIGatewayProxyEvent & { foo: string }
) => {
  console.log("Foo", event.foo);

  return {
    body: "Hello World",
    statusCode: 200,
  };
};

export const handlerComposed = composeHandler(
  fooMiddleware(),
  cors(),
  helloWorldEvent  // <- not happy
);
 ```

Anything stick out?

**Comment by nateiler** [comment]
I noticed that the first party cors middleware uses `APIGatewayEvent` and not `APIGatewayProxyEvent` which is what my middleware was using.  Changing that along with changing `fooMiddleware` to `fooMiddleware()` seemed to fix the second scenario.

```typescript
import { Context, APIGatewayEvent, APIGatewayProxyResult } from "aws-lambda";
import { PromiseHandler } from "@lambda-middleware/utils";
import { composeHandler } from "@lambda-middleware/compose";
import { cors } from "@lambda-middleware/cors";

const fooMiddleware = () => <E extends APIGatewayEvent>(
  handler: PromiseHandler<E & { foo: string }, APIGatewayProxyResult>
): PromiseHandler<E, APIGatewayProxyResult> => async (
  event: E,
  context: Context
) => {
  return handler({ ...event, foo: "bar" }, context);
};

const helloWorldEvent = async (event: APIGatewayEvent & { foo: string }) => {
  console.log("Foo", event.foo);

  return {
    body: "Hello World",
    statusCode: 200,
  };
};

export const handlerComposed = composeHandler(
  cors(),
  fooMiddleware(),
  helloWorldEvent
);
```

Still looking into the first...

**Comment by dbartholomae** [comment]
Unfortunately, this is a limitation of TypeScript related to generics and not solvable by this library. You can find the relevant links and discussions here:
https://github.com/dbartholomae/lambda-middleware/issues/36#issuecomment-720755530
