### ISSUE TITLE
JsonDeserializer does not accept content-type header with charset

### ISSUE THREAD

**Issue by buresmi7** [dbartholomae/lambda-middleware#61]
## Describe the bug
JsonDeserializer does not accept content-type header with charset

## To Reproduce
use header: `Content-Type: application/json; charset=utf-8`

## Expected behavior
`bodyObject` should not be null

## Additional context
nope

**Comment by dbartholomae** [comment]
Thanks! :)

**Comment by buresmi7** [comment]
> Thanks! :)

Thanks for nice library :)
