### ISSUE TITLE
JSONSchema validator with AJV

### ISSUE THREAD

**Issue by Soviut** [dbartholomae/lambda-middleware#67]
**Is your feature request related to a problem? Please describe.**

I've been using [AJV](https://ajv.js.org/) to validate my request payloads. I could see this being easily adapted to an official lambda-middleware.

JSONSchema is a well documented spec. AJV can return very detailed errors. It also doesn't require adapting your code to use classes.

** Would you be willing to help with a PR? **
- [X] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like

Turn the following into middleware.

```typescript
// JSONSchema format
const bodySchema = {
  type: 'object',
  properties: {
    body: { type: 'string' },
    header: { type: 'string' },
    footer: { type: 'string' },
    encoding: { type: 'string' },
    options: { type: 'object', additionalProperties: true },
  },
  required: ['body'],
  additionalProperties: false,
}
const ajv = new Ajv()
const validate = ajv.compile(bodySchema)

const payload = JSON.parse(event.body)
const valid = validate(payload)
if (!valid) {
  console.log(validate.errors)
}
```

## Describe alternatives you've considered

What I'm doing now is already the alternative.

**Comment by dbartholomae** [comment]
I'm open to a middleware added here. It would need to conform to a similar interface as the existing validation middleware, though. Having the same tests could be a good way to ensure that:
https://github.com/dbartholomae/lambda-middleware/blob/main/packages/class-validator/src/classValidator.test.ts
