### ISSUE TITLE
Can we use different event type? Now strict to `APIGatewayEvent `

### ISSUE THREAD

**Issue by Gabiras12** [dbartholomae/lambda-middleware#69]
Thanks for this libary.

Can we use a different lambda event type?
I would like to have the event as `APIGatewayProxyEventV2WithJWTAuthorizer` for example.

Thanks

**Comment by dbartholomae** [comment]
Hi! Thanks for reaching out! I'm open to PRs around this. The original approach I tried was using TypeScript generics, but unfortunately TypeScript doesn't yet possess enough capabilities to correctly handle them in these situations:
https://github.com/dbartholomae/lambda-middleware/issues/36#issuecomment-718975053

I'm open to other ideas how to solve this, though.
