### ISSUE TITLE
Can you please show how to add cors() to a compose chain?

### ISSUE THREAD

**Issue by drmikecrowe** [dbartholomae/lambda-middleware#72]
**Is your feature request related to a problem? Please describe.**
I'm trying to add the `cors` middleware to a compose chain, and can't seem to find the right combination.  Here's my current attempt:

```ts
const corsConfig: CorsMiddlewareOptions = {
  allowedHeaders: ['*'],
  cacheControl: 'max-age: 300',
  allowCredentials: true,
  exposedHeaders: ['X-Custom-Header'],
  maxAge: 300,
  allowedMethods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'],
  optionsSuccessStatus: 204,
  allowedOrigins: ['https://mysite.com'],
  preflightContinue: false,
}

export const standardHttp = compose<APIGatewayEvent, APIGatewayProxyResult>(
  createJWTForLocal,
  typeormInitializer,
  doNotWait(),
  jsonSerializer(),
  jsonDeserializer(),
  timingLogMiddleware(logDuration),
  errorHandler,
  cors(corsConfig)
)
```

** Would you be willing to help with a PR? **
- [X] Yes, absolutely
- [ ] Yes, with some guidance
- [ ] Unfortunately no time :'-(

## Describe the solution you'd like
Ideally, I'd like to add `cors` to this chain to add to all lambda functions

## Describe alternatives you've considered
None

**Comment by dbartholomae** [comment]
Thanks! What's the problem you run into?

**Comment by drmikecrowe** [comment]
I'm seeing stuff like this:

```log
    TypeError: Cannot read properties of undefined (reading 'toLowerCase')
      20 |   async (event: APIGatewayEvent, context: Context): Promise<APIGatewayProxyResult> => {
      21 |     logger('Running handler')
    > 22 |     const response = await handler(event, context)
         |                            ^
      23 |     logger('Response received')
      24 |     if (response === undefined) {
      25 |       logger('Undefined response, returning statusCode 204')
      at node_modules/@lambda-middleware/cors/src/cors.ts:38:26
```

**Comment by dbartholomae** [comment]
The line with the error is the line that calls your handler, so the error might be related to the handler. Could you please share a small repo with the error with the full context including a handler? Thanks! :)
